#!/bin/bash

# Setup sudoers configuration for NovaPanel
# This script must be run as root

set -e

echo "=========================================="
echo "NovaPanel Sudoers Setup"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "❌ This script must be run as root"
    echo "   Please run: sudo bash $0"
    exit 1
fi

# Check if novapanel user exists
if ! id "novapanel" &>/dev/null; then
    echo "⚠️  Warning: User 'novapanel' does not exist"
    echo "   Creating novapanel user..."
    useradd -r -m -d /opt/novapanel -s /bin/bash novapanel
    echo "✓ Created user 'novapanel'"
    echo ""
fi

# Function to get the real path of a command
get_cmd_path() {
    local cmd="$1"
    local path
    path=$(command -v "$cmd" 2>/dev/null || which "$cmd" 2>/dev/null)
    if [ -n "$path" ]; then
        # Resolve symlinks to get the real path
        readlink -f "$path" 2>/dev/null || echo "$path"
    else
        echo ""
    fi
}

# Detect command paths (supports both /bin and /usr/bin locations)
SYSTEMCTL_PATH=$(get_cmd_path systemctl)
MKDIR_PATH=$(get_cmd_path mkdir)
CHOWN_PATH=$(get_cmd_path chown)
CHMOD_PATH=$(get_cmd_path chmod)
CRONTAB_PATH=$(get_cmd_path crontab)
LN_PATH=$(get_cmd_path ln)
RM_PATH=$(get_cmd_path rm)
CP_PATH=$(get_cmd_path cp)
MV_PATH=$(get_cmd_path mv)
NGINX_PATH=$(get_cmd_path nginx)
NAMED_CHECKCONF_PATH=$(get_cmd_path named-checkconf)
NAMED_CHECKZONE_PATH=$(get_cmd_path named-checkzone)
PURE_PW_PATH=$(get_cmd_path pure-pw)
BASH_PATH=$(get_cmd_path bash)

# Set default paths for commands that might not be installed yet
[ -z "$SYSTEMCTL_PATH" ] && SYSTEMCTL_PATH="/usr/bin/systemctl"
[ -z "$MKDIR_PATH" ] && MKDIR_PATH="/usr/bin/mkdir"
[ -z "$CHOWN_PATH" ] && CHOWN_PATH="/usr/bin/chown"
[ -z "$CHMOD_PATH" ] && CHMOD_PATH="/usr/bin/chmod"
[ -z "$CRONTAB_PATH" ] && CRONTAB_PATH="/usr/bin/crontab"
[ -z "$LN_PATH" ] && LN_PATH="/usr/bin/ln"
[ -z "$RM_PATH" ] && RM_PATH="/usr/bin/rm"
[ -z "$CP_PATH" ] && CP_PATH="/usr/bin/cp"
[ -z "$MV_PATH" ] && MV_PATH="/usr/bin/mv"
[ -z "$NGINX_PATH" ] && NGINX_PATH="/usr/sbin/nginx"
[ -z "$NAMED_CHECKCONF_PATH" ] && NAMED_CHECKCONF_PATH="/usr/sbin/named-checkconf"
[ -z "$NAMED_CHECKZONE_PATH" ] && NAMED_CHECKZONE_PATH="/usr/sbin/named-checkzone"
[ -z "$PURE_PW_PATH" ] && PURE_PW_PATH="/usr/bin/pure-pw"
[ -z "$BASH_PATH" ] && BASH_PATH="/usr/bin/bash"

echo "Detected command paths:"
echo "  systemctl: $SYSTEMCTL_PATH"
echo "  mkdir: $MKDIR_PATH"
echo "  chown: $CHOWN_PATH"
echo "  chmod: $CHMOD_PATH"
echo "  crontab: $CRONTAB_PATH"
echo "  ln: $LN_PATH"
echo "  rm: $RM_PATH"
echo "  cp: $CP_PATH"
echo "  mv: $MV_PATH"
echo "  nginx: $NGINX_PATH"
echo "  named-checkconf: $NAMED_CHECKCONF_PATH"
echo "  named-checkzone: $NAMED_CHECKZONE_PATH"
echo "  pure-pw: $PURE_PW_PATH"
echo "  bash: $BASH_PATH"
echo ""

# Create sudoers configuration with detected paths
echo "Configuring sudo permissions for novapanel user..."
cat > /etc/sudoers.d/novapanel <<EOF
# NovaPanel Sudoers Configuration
# Generated by setup-sudoers.sh
# Single VPS Model: Only ONE Linux user (novapanel) exists
# No user creation/modification/deletion commands allowed (useradd/usermod/userdel)

# Service management - reload only (no restart/stop for safety)
novapanel ALL=(ALL) NOPASSWD: ${SYSTEMCTL_PATH} reload nginx
novapanel ALL=(ALL) NOPASSWD: ${SYSTEMCTL_PATH} reload php*-fpm
novapanel ALL=(ALL) NOPASSWD: ${SYSTEMCTL_PATH} reload bind9
novapanel ALL=(ALL) NOPASSWD: ${SYSTEMCTL_PATH} reload named

# File and directory operations
novapanel ALL=(ALL) NOPASSWD: ${MKDIR_PATH}
novapanel ALL=(ALL) NOPASSWD: ${CHOWN_PATH}
novapanel ALL=(ALL) NOPASSWD: ${CHMOD_PATH}
novapanel ALL=(ALL) NOPASSWD: ${LN_PATH}
novapanel ALL=(ALL) NOPASSWD: ${RM_PATH}
novapanel ALL=(ALL) NOPASSWD: ${CP_PATH}
novapanel ALL=(ALL) NOPASSWD: ${MV_PATH}

# Cron management
novapanel ALL=(ALL) NOPASSWD: ${CRONTAB_PATH}

# Configuration validation
novapanel ALL=(ALL) NOPASSWD: ${NGINX_PATH} -t
novapanel ALL=(ALL) NOPASSWD: ${NAMED_CHECKCONF_PATH}
novapanel ALL=(ALL) NOPASSWD: ${NAMED_CHECKZONE_PATH}

# FTP user management
novapanel ALL=(ALL) NOPASSWD: ${PURE_PW_PATH}

# Shell access for advanced operations
novapanel ALL=(ALL) NOPASSWD: ${BASH_PATH}
EOF

chmod 440 /etc/sudoers.d/novapanel

# Validate sudoers file
echo "Validating sudoers configuration..."
if visudo -c -f /etc/sudoers.d/novapanel > /dev/null 2>&1; then
    echo "✓ Sudoers file validated successfully"
else
    echo "❌ Error: Sudoers file validation failed"
    echo "   Please check /etc/sudoers.d/novapanel for syntax errors"
    rm -f /etc/sudoers.d/novapanel
    exit 1
fi

echo ""
echo "=========================================="
echo "✅ Sudoers configuration complete!"
echo "=========================================="
echo ""
echo "The novapanel user can now run sudo commands without a password."
echo "Configuration file: /etc/sudoers.d/novapanel"
echo ""
echo "You can now use NovaPanel without sudo password prompts."
echo ""
